version: "3.7" 
services: 
  db: 
    image: mysql:5.7 
    restart: always
    container_name: mysql-test
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=loveframe
      - MYSQL_USER=jaehyun
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d